base_url = "https://blog.katsyoshi.org"
build_search_index = true
compile_sass = true
generate_feeds = true
description = "It's a memos."

title = "katsyoshi のめもみたいなの"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
